apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roboFullFillOrder
  labels:
    run: roboFullFillOrder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: roboFullFillOrder
    spec:
      containers:
      - name: roboFullFillOrder
        image: sabbour/fulfillorderack:latest
        imagePullPolicy: Always
        ports:
          - name: port1
            containerPort: 5672
            protocol: TCP
        env:
        - name: TEAMNAME
          value: ROBO-CLUSTERS
        - name: MONGOURL
          value: mongodb://$(MONGODB_URL):$(MONGODB_PORT)
 
---
 
kind: Service
apiVersion: v1
metadata:
  name: roboFullFillOrderService
  annotations:
     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: roboFullFillOrderService
  ports:
  - protocol: TCP
    port: 443
    targetPort: $(TARGET_PORT)
  clusterIP: $(CLUSTER_IP)
  loadBalancerIP: $(LOAD_BALANCER_IP)
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.1